// Code generated by golex. DO NOT EDIT.

package lexico

import (
	"bytes"
	"fmt"
	"go/token"
	"strconv"
	"unicode"

	"container/list"
	"modernc.org/golex/lex"
)

var LValores *list.List

//var list0 *list.List

/*
type ParamComandos struct {
    nombre string
    ruta   string
}

var parametros ParamComandos

func Retorno() ParamComandos{
	return parametros
}
func Datos(dat ParamComandos){
	 parametros=dat
}
*/

var Parametros Tokenn

// Allocate Character classes anywhere in [0x80, 0xFF].
const (
	classUnicodeLeter = iota + 0x80
	classUnicodeDigit
	classOther
)

// Parser token values.
const (
	FUNC = iota + 0xE002
	INT
	NEG
	dir

	VARI     = iota + 0xE002
	DIAGONAL = iota + 0xE002

	concatenar
	comentario
	identificador
	espacio
	letra
	//---------------------------------------------
	exec
	path
	direccion
	direccomi
	flecha
	pause
	//----------------------------------------------
	mkdisk
	archivo
	name
	sizee
	unit
	typee
	tipo
	deletee
	add
	fit

	rmdisk
	fdisk
	mount
	unmount
	rep
)

func valor(val int) int {
	return val
}

// For pretty printing.
func str(r rune) string {
	switch r {
	case FUNC:
		return "FUNC"
	case INT:
		return "INT"
	case VARI:
		return "VARI"
	case NEG:
		return "NEG"
	case DIAGONAL:
		return "DIAGONAL"
	case dir:
		return "dir"
	case direccion:
		return "direccion"
	case direccomi:
		return "direccomi"
	case flecha:
		return "flecha"
	case archivo:
		return "archivo"
	case comentario:
		return "comentario"
	case identificador:
		return "identificador"
	case concatenar:
		return "concatenar"
	case letra:
		return "letra"
	case tipo:
		return "tipo"

	case exec:
		return "exec"
	case pause:
		return "pause"
	case mkdisk:
		return "mkdisk"
	case rmdisk:
		return "rmdisk"
	case fdisk:
		return "fdisk"
	case mount:
		return "mount"
	case unmount:
		return "unmount"
	case rep:
		return "rep"

	case sizee:
		return "size"
	case path:
		return "path"
	case name:
		return "name"
	case unit:
		return "unit"
	case typee:
		return "typee"
	case deletee:
		return "deletee"
	case add:
		return "add"
	case fit:
		return "fit"

	case lex.RuneEOF:
		return "EOF"

	default:
		return "Error"
	}

	//return fmt.Sprintf("%q", r)
}

type lexer struct {
	*lex.Lexer
}

func (l *lexer) char(r int) lex.Char {
	return lex.NewChar(l.First.Pos(), rune(r))
}

func rune2Class(r rune) int {
	if r >= 0 && r < 0x80 { // Keep ASCII as it is.
		return int(r)
	}

	if unicode.IsLetter(r) {
		return classUnicodeLeter
	}

	if unicode.IsDigit(r) {
		return classUnicodeDigit
	}

	return classOther
}

func Alexico(entrada string) int {

	fset := token.NewFileSet()
	file := fset.AddFile("example.go", -1, len(entrada))
	src := bytes.NewBufferString(entrada)
	lx, err := lex.New(file, src, lex.RuneClass(rune2Class))
	if err != nil {
		panic(err)
	}

	l := &lexer{lx}

	LValores = list.New()
	//LValores := New()

	for {
		c := l.scan()
		//fmt.Printf("%v --> %s\n", str(c.Rune), l.TokenBytes(nil))

		//LValores.PushBack(str(c.Rune))
		LValores.PushBack(string(l.TokenBytes(nil)))

		/*if str(c.Rune)=="path"{
			//fmt.Printf("*** dentro del metodo: %s \n",l.TokenBytes(nil))
			//san:=string(l.Token())
		Parametros.Set_Path(l.TokenBytes(nil))
		}*/

		if str(c.Rune) == "Error" {
			fmt.Printf("%v --> %s\n", str(c.Rune), l.TokenBytes(nil))
			return 1

		}

		if c.Rune == lex.RuneEOF {

			/*for temp := LValores.Front(); temp != nil; temp = temp.Next() {
			    fmt.Println(">>>>>",temp.Value)
						}*/
			return 0
		}

	}

}

func (l *lexer) scan() lex.Char {
	c := l.Enter()

yystate0:
	yyrule := -1
	_ = yyrule
	c = l.Rule0()

	goto yystart1

yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	case 24:
		goto yyrule24
	case 25:
		goto yyrule25
	case 26:
		goto yyrule26
	case 27:
		goto yyrule27
	case 28:
		goto yyrule28
	case 29:
		goto yyrule29
	case 30:
		goto yyrule30
	case 31:
		goto yyrule31
	}
yystate1:
	c = l.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate3
	case c == '#':
		goto yystate6
	case c == '-':
		goto yystate7
	case c == '/':
		goto yystate11
	case c == '\\':
		goto yystate27
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	case c == 'a':
		goto yystate29
	case c == 'd':
		goto yystate38
	case c == 'e':
		goto yystate44
	case c == 'f':
		goto yystate48
	case c == 'l':
		goto yystate55
	case c == 'm':
		goto yystate57
	case c == 'n':
		goto yystate67
	case c == 'p':
		goto yystate71
	case c == 'r':
		goto yystate78
	case c == 's':
		goto yystate86
	case c == 't':
		goto yystate90
	case c == 'u':
		goto yystate94
	case c == '{':
		goto yystate103
	case c >= '0' && c <= '9':
		goto yystate19
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'b' || c == 'c' || c >= 'g' && c <= 'k' || c == 'o' || c == 'q' || c >= 'v' && c <= 'z':
		goto yystate20
	}

yystate2:
	c = l.Next()
	yyrule = 1
	l.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate4
	}

yystate4:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate5
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= '!' || c >= '#' && c <= 'ÿ':
		goto yystate4
	}

yystate5:
	c = l.Next()
	yyrule = 28
	l.Mark()
	switch {
	default:
		goto yyrule28
	case c == '"':
		goto yystate5
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= '!' || c >= '#' && c <= 'ÿ':
		goto yystate4
	}

yystate6:
	c = l.Next()
	yyrule = 29
	l.Mark()
	switch {
	default:
		goto yyrule29
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate6
	}

yystate7:
	c = l.Next()
	yyrule = 20
	l.Mark()
	switch {
	default:
		goto yyrule20
	case c == '-':
		goto yystate8
	case c == '>':
		goto yystate10
	case c >= '0' && c <= '9':
		goto yystate9
	}

yystate8:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate8
	case c >= '0' && c <= '9':
		goto yystate9
	}

yystate9:
	c = l.Next()
	yyrule = 24
	l.Mark()
	switch {
	default:
		goto yyrule24
	case c >= '0' && c <= '9':
		goto yystate9
	}

yystate10:
	c = l.Next()
	yyrule = 18
	l.Mark()
	goto yyrule18

yystate11:
	c = l.Next()
	yyrule = 17
	l.Mark()
	switch {
	default:
		goto yyrule17
	case c == '/':
		goto yystate12
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate13
	}

yystate12:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '/':
		goto yystate12
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate13
	}

yystate13:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '/':
		goto yystate14
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate13
	}

yystate14:
	c = l.Next()
	yyrule = 27
	l.Mark()
	switch {
	default:
		goto yyrule27
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate15
	}

yystate15:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate16
	case c == '/':
		goto yystate14
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate15
	}

yystate16:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate17
	}

yystate17:
	c = l.Next()
	yyrule = 27
	l.Mark()
	switch {
	default:
		goto yyrule27
	case c >= '0' && c <= '9' || c == '\u0081':
		goto yystate17
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate18
	}

yystate18:
	c = l.Next()
	yyrule = 27
	l.Mark()
	switch {
	default:
		goto yyrule27
	case c == '.':
		goto yystate16
	case c == '/':
		goto yystate14
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate18
	}

yystate19:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c >= '0' && c <= '9':
		goto yystate19
	}

yystate20:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate21:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'd':
		goto yystate22
	}

yystate22:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 's':
		goto yystate23
	}

yystate23:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'k':
		goto yystate24
	}

yystate24:
	c = l.Next()
	yyrule = 26
	l.Mark()
	goto yyrule26

yystate25:
	c = l.Next()
	yyrule = 25
	l.Mark()
	goto yyrule25

yystate26:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate27:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate28
	}

yystate28:
	c = l.Next()
	yyrule = 19
	l.Mark()
	goto yyrule19

yystate29:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'd':
		goto yystate30
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate30:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'd':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate31:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '-':
		goto yystate32
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate32:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '>':
		goto yystate33
	}

yystate33:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'a':
		goto yystate35
	case c >= '0' && c <= '9':
		goto yystate34
	}

yystate34:
	c = l.Next()
	yyrule = 30
	l.Mark()
	switch {
	default:
		goto yyrule30
	case c >= '0' && c <= '9':
		goto yystate34
	}

yystate35:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'd':
		goto yystate36
	}

yystate36:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'd':
		goto yystate37
	}

yystate37:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '-':
		goto yystate32
	}

yystate38:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate39
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate39:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'l':
		goto yystate40
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate40:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate41
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate41:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate42:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate43:
	c = l.Next()
	yyrule = 15
	l.Mark()
	switch {
	default:
		goto yyrule15
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate44:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'x':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'w' || c == 'y' || c == 'z' || c == '\u0081':
		goto yystate26
	}

yystate45:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate46:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'c':
		goto yystate47
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate47:
	c = l.Next()
	yyrule = 3
	l.Mark()
	switch {
	default:
		goto yyrule3
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate48:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'd':
		goto yystate49
	case c == 'i':
		goto yystate53
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate49:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'i':
		goto yystate50
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate50:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 's':
		goto yystate51
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate51:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'k':
		goto yystate52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate52:
	c = l.Next()
	yyrule = 6
	l.Mark()
	switch {
	default:
		goto yyrule6
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate53:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate54:
	c = l.Next()
	yyrule = 16
	l.Mark()
	switch {
	default:
		goto yyrule16
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate55:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == '}':
		goto yystate56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate56:
	c = l.Next()
	yyrule = 22
	l.Mark()
	goto yyrule22

yystate57:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'k':
		goto yystate58
	case c == 'o':
		goto yystate63
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate58:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'd':
		goto yystate59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate59:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'i':
		goto yystate60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate60:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 's':
		goto yystate61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate61:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'k':
		goto yystate62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate62:
	c = l.Next()
	yyrule = 4
	l.Mark()
	switch {
	default:
		goto yyrule4
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate63:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'u':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate64:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'n':
		goto yystate65
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate65:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate66
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate66:
	c = l.Next()
	yyrule = 7
	l.Mark()
	switch {
	default:
		goto yyrule7
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate67:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'a':
		goto yystate68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate68:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'm':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate69:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate70:
	c = l.Next()
	yyrule = 12
	l.Mark()
	switch {
	default:
		goto yyrule12
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate71:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'a':
		goto yystate72
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate72:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate73
	case c == 'u':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'v' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate73:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'h':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate74:
	c = l.Next()
	yyrule = 11
	l.Mark()
	switch {
	default:
		goto yyrule11
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate75:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 's':
		goto yystate76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate76:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate77:
	c = l.Next()
	yyrule = 2
	l.Mark()
	switch {
	default:
		goto yyrule2
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate78:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate79
	case c == 'm':
		goto yystate81
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate79:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'p':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate80:
	c = l.Next()
	yyrule = 9
	l.Mark()
	switch {
	default:
		goto yyrule9
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate81:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'd':
		goto yystate82
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate82:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'i':
		goto yystate83
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate83:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 's':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate84:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'k':
		goto yystate85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate85:
	c = l.Next()
	yyrule = 5
	l.Mark()
	switch {
	default:
		goto yyrule5
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate86:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'i':
		goto yystate87
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate87:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'z':
		goto yystate88
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'y' || c == '\u0081':
		goto yystate26
	}

yystate88:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate89:
	c = l.Next()
	yyrule = 10
	l.Mark()
	switch {
	default:
		goto yyrule10
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate90:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'y':
		goto yystate91
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z' || c == '\u0081':
		goto yystate26
	}

yystate91:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'p':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate92:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'e':
		goto yystate93
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate93:
	c = l.Next()
	yyrule = 14
	l.Mark()
	switch {
	default:
		goto yyrule14
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate94:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'n':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate95:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'i':
		goto yystate96
	case c == 'm':
		goto yystate98
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate96:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate97
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate97:
	c = l.Next()
	yyrule = 13
	l.Mark()
	switch {
	default:
		goto yyrule13
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate98:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'o':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate99:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'u':
		goto yystate100
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate100:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 'n':
		goto yystate101
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate101:
	c = l.Next()
	yyrule = 31
	l.Mark()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c == 't':
		goto yystate102
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate102:
	c = l.Next()
	yyrule = 8
	l.Mark()
	switch {
	default:
		goto yyrule8
	case c == '.':
		goto yystate21
	case c == '/':
		goto yystate25
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0081':
		goto yystate26
	}

yystate103:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == 'e':
		goto yystate56
	}

yyrule1: // [ \t\r\n]+

	goto yystate0
yyrule2: // pause
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(pause)
		}
		goto yystate0
	}
yyrule3: // exec
	{
		{ /*LValores.PushFront("exec") ;*/
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(exec)
		}
		goto yystate0
	}
yyrule4: // mkdisk
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(mkdisk)
		}
		goto yystate0
	}
yyrule5: // rmdisk
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(rmdisk)
		}
		goto yystate0
	}
yyrule6: // fdisk
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(fdisk)
		}
		goto yystate0
	}
yyrule7: // mount
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(mount)
		}
		goto yystate0
	}
yyrule8: // unmount
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(unmount)
		}
		goto yystate0
	}
yyrule9: // rep
	{
		{
			Parametros.Set_Comando(string(l.TokenBytes(nil)))
			return l.char(rep)
		}
		goto yystate0
	}
yyrule10: // size
	{
		{ /*Parametros.Set_Size(string(l.TokenBytes(nil)));*/
			return l.char(sizee)
		}
		goto yystate0
	}
yyrule11: // path
	{
		{ /*Parametros.Set_Path(string(l.TokenBytes(nil)));*/
			return l.char(path)
		}
		goto yystate0
	}
yyrule12: // name
	{
		{ /*Parametros.Set_Name(string(l.TokenBytes(nil)));*/
			return l.char(name)
		}
		goto yystate0
	}
yyrule13: // unit
	{
		{ /*Parametros.Set_Unit(string(l.TokenBytes(nil)));*/
			return l.char(unit)
		}
		goto yystate0
	}
yyrule14: // "type"
	{
		{ /*Parametros.Set_Tipo(string(l.TokenBytes(nil)));*/
			return l.char(typee)
		}
		goto yystate0
	}
yyrule15: // "delete"
	{
		{
			return l.char(deletee)
		}
		goto yystate0
	}
yyrule16: // fit
	{
		{
			return l.char(fit)
		}
		goto yystate0
	}
yyrule17: // "/"
	{
		return l.char(DIAGONAL)
	}
yyrule18: // "->"
	{
		return l.char(flecha)
	}
yyrule19: // "\*"
	{
		return l.char(concatenar)
	}
yyrule20: // "-"
	{
		{
		}
		goto yystate0
	}
yyrule21: // {letter}
	{
		{
			if string(l.TokenBytes(nil)) == "p" || string(l.TokenBytes(nil)) == "e" || string(l.TokenBytes(nil)) == "l" {
				Parametros.Set_Tipo(string(l.TokenBytes(nil)))
			} else {
				Parametros.Set_Unit(string(l.TokenBytes(nil)))
				return l.char(letra)
			}
		}
		goto yystate0
	}
yyrule22: // {tipo}
	{
		{ /*Parametros.Set_Tipo(string(l.TokenBytes(nil)));*/
			return l.char(tipo)
		}
		goto yystate0
	}
yyrule23: // {int}
	{
		{
			if num, err := strconv.ParseInt(string(l.TokenBytes(nil)), 10, 64); err == nil {
				Parametros.Set_Size(num)
			} else {
			}
			return l.char(INT)
		}
	}
yyrule24: // {negativo}
	{
		return l.char(NEG)
	}
yyrule25: // {dir}
	{
		return l.char(dir)
	}
yyrule26: // {archivo}
	{
		{
			Parametros.Set_Name(string(l.TokenBytes(nil)))
			return l.char(archivo)
		}
		goto yystate0
	}
yyrule27: // {direccion}
	{
		{
			Parametros.Set_Path(string(l.TokenBytes(nil)))
			return l.char(direccion)
		}
		goto yystate0
	}
yyrule28: // {direccomi}
	{
		{
			Parametros.Set_Path(string(l.TokenBytes(nil)))
			return l.char(direccomi)
		}
		goto yystate0
	}
yyrule29: // {comentario}
	{
		return l.char(comentario)
	}
yyrule30: // {add}
	{
		{
			Parametros.Set_Add(string(l.TokenBytes(nil)))
			return l.char(add)
		}
		goto yystate0
	}
yyrule31: // {identifier}
	if true { // avoid go vet determining the below panic will not be reached
		{
			if string(l.TokenBytes(nil)) == "bf" || string(l.TokenBytes(nil)) == "ff" || string(l.TokenBytes(nil)) == "wf" {
				Parametros.Set_Fit(string(l.TokenBytes(nil)))
			} else if string(l.TokenBytes(nil)) == "fast" || string(l.TokenBytes(nil)) == "full" {
				Parametros.Set_Delete(string(l.TokenBytes(nil)))
			} else if string(l.TokenBytes(nil)) == "mbr" || string(l.TokenBytes(nil)) == "disk" || string(l.TokenBytes(nil)) == "sb" {
				Parametros.Set_NameGrafic(string(l.TokenBytes(nil)))
			} else {
				Parametros.Set_Namefd(string(l.TokenBytes(nil)))
			}

			return l.char(identificador)
		}
	}
	panic("unreachable")

yyabort: // no lexem recognized
	//
	// silence unused label errors for build and satisfy go vet reachability analysis
	//
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
	}

	if c, ok := l.Abort(); ok {
		return l.char(c)
	}
	goto yyAction
}
